### ISSUE TITLE
"symlink-install" Error

### ISSUE THREAD

**Issue by fentuoli** [snt-arg/lidar_situational_graphs#1]
Hi, I appreciate your wonderful work! I try to deploy it on my ubuntu20.04 system, when I executed this command 
```
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo
```
I got this error:
![Screenshot 2024-04-10 18:33:28](https://github.com/snt-arg/lidar_s_graphs/assets/36686362/aa11f577-4537-49ba-b333-2632e4d0c5c4)
I have no idea on solving this problem, do have any advice?

**Comment by hridaybavle** [comment]
Hello @fentuoli,

I think the error is just related to your system. You can try to clear your `build` and `install` folders and try to build again. Additionally also try to reduce the number of parallel threads when doing colcon build using this command: `colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo --parallel-workers 2`.

I reduced the threads to `2` this will build the code quite slowly.

**Comment by fentuoli** [comment]
Thanks for your reply. I tried a lot and gave up deploying it on my local environment. I use docker and it works well.

**Comment by hridaybavle** [comment]
Okay good to know, will close the issue.
