### ISSUE TITLE
Cannot load pth of GNN

### ISSUE THREAD

**Issue by mga-97** [snt-arg/lidar_situational_graphs#10]
When trying to run from docker:
`ros2 launch lidar_situational_graphs s_graphs_launch.py compute_odom:=false odom_frame:=/odom lidar_topic:=/camera/depth/color/points base_frame:=mobile_base_body_link`

I get this error:

[situational_graphs_reasoning-2]   self.model.load_state_dict(torch.load(path))
[situational_graphs_reasoning-2] Traceback (most recent call last):
[situational_graphs_reasoning-2]   File "/root/workspaces/install/situational_graphs_reasoning/lib/situational_graphs_reasoning/situational_graphs_reasoning", line 33, in <module>
[situational_graphs_reasoning-2]     sys.exit(load_entry_point('situational-graphs-reasoning==0.0.0', 'console_scripts', 'situational_graphs_reasoning')())
[situational_graphs_reasoning-2]   File "/root/workspaces/install/situational_graphs_reasoning/lib/python3.10/site-packages/situational_graphs_reasoning/situational_graphs_reasoning_node.py", line 545, in main
[situational_graphs_reasoning-2]     situational_graphs_reasoning_node = SituationalGraphReasoningNode()
[situational_graphs_reasoning-2]   File "/root/workspaces/install/situational_graphs_reasoning/lib/python3.10/site-packages/situational_graphs_reasoning/situational_graphs_reasoning_node.py", line 81, in __init__
[situational_graphs_reasoning-2]     self.gnns["room"].load_model()
[situational_graphs_reasoning-2]   File "/root/workspaces/install/situational_graphs_reasoning/lib/python3.10/site-packages/situational_graphs_reasoning/GNNWrapper.py", line 635, in load_model
[situational_graphs_reasoning-2]     self.model.load_state_dict(torch.load(path))
[situational_graphs_reasoning-2]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2584, in load_state_dict
[situational_graphs_reasoning-2]     raise RuntimeError(
[situational_graphs_reasoning-2] RuntimeError: Error(s) in loading state_dict for Model_vMiniEncoder:
[situational_graphs_reasoning-2] 	Missing key(s) in state_dict: "encoder_1.nodes_GATConv1.ws__ws_same_room__ws.lin.weight", "encoder_2.nodes_GATConv1.ws__ws_same_room__ws.lin.weight". 
[situational_graphs_reasoning-2] 	Unexpected key(s) in state_dict: "encoder_1.nodes_GATConv1.ws__ws_same_room__ws.lin_src.weight", "encoder_1.nodes_GATConv1.ws__ws_same_room__ws.lin_dst.weight", "encoder_2.nodes_GATConv1.ws__ws_same_room__ws.lin_src.weight", "encoder_2.nodes_GATConv1.ws__ws_same_room__ws.lin_dst.weight".

**Comment by hridaybavle** [comment]
@JoseAndresMR do you have any idea of this error?

**Comment by hridaybavle** [comment]
Hello @mga-97,

How are you building the docker, it seems to me that your docker has cuda installed, is that the case?

Can you please try building the humble version of the docker, I think the foxy_noetic docker version might have some issues. 
For building the humbler version of the docker go to the folder `/docker/humble` and then do `docker build -t sntarg/s_graphs .
`

**Comment by mga-97** [comment]
Hi, this image is the humble version. However I did have to comment out the "colcon build" part as the building was freezing at that stage, once I was in the container I could build it correctly (not sure why this is), presumably the resulting image is exactly the same. For now I can get around the error by adding the keys with the expected name using the weights from the unexpected names, right now I can't tell if this is actually fixing the situation as I am still learning about your method and I am not running on RGB-D pointcloud and not on LIDAR.

**Comment by mga-97** [comment]
Never mind, it seems I just needed to run setup.sh
