### ISSUE TITLE
Run S-Graph on my own Data

### ISSUE THREAD

**Issue by fentuoli** [snt-arg/lidar_situational_graphs#2]
Hi, I record my own data using livox mid360, and I don't provide imu and odom. I set 'compute_odom' to true in yaml file. But 's_graph' node cannot run.  The process blocks as following.
![2024-04-15_21-46](https://github.com/snt-arg/lidar_s_graphs/assets/36686362/dd360220-34b9-4db9-b074-356e0f1fd34c)
I notice the 'scan_matching_odometry_node' subscribes two topics "velodyne_points' and 'odom'. So is odom topic necessary? 
In addition, besides modifying the transformation using static_transform_publisher and providing laser and odom topics, do I need to modify anything else?

**Comment by hridaybavle** [comment]
Hello,

Can you share with me your rosbag? I think your problem is mostly because the scan_matching_odom_node is not receiving the data correctly. And therefore the s_graphs_node doesn’t have an initial guess from the odometry.

**Comment by fentuoli** [comment]
Thanks for your quick reply, I found that it was caused by the false laser msg format. I didn't provide "sensor_msgs/PointCloud2" msg format. It's a stupid error, and now I can run it on my own data smoothly, thanks a lot!

**Comment by fentuoli** [comment]
Sorry to bother again, I have another problem. I try to use ' rosservice call /voxblox_skeletonizer/save_map "file_path: '/root/Downloads/test.pcd'" ' to save pcd map, but the results is empty, there is no points in test.pcd. 
In addition, I cannot find '/s_graphs/dump' service, all services pulished as following:
![2024-04-16_17-12](https://github.com/snt-arg/lidar_s_graphs/assets/36686362/58981b47-f2a7-4735-a543-9caa2d400370)
I want to get details about different layers, it will be more convenient if I can call dump service!

**Comment by hridaybavle** [comment]
Hello, 

You are looking into the ros1 services thats why you dont see the s_graphs/dump_map service. You can source the s_graphs_ros2_ws and then do `ros2 service list` and you will find the  `save_map` service. 

Then you can use the following command and it will save your map. 
`ros2 service call /s_graphs/save_map s_graphs/srv/SaveMap "{utm: False, resolution: 0.0, destination: "/home/example/map.pcd"}"`. Change `/home/example` to your usecase.

**Comment by fentuoli** [comment]
Thanks a lot, service "/s_graphs/save_map" works well. But "/s_graphs/dump" seems using too much time to execute, the process blocks as following:
![2024-04-16_19-35](https://github.com/snt-arg/lidar_s_graphs/assets/36686362/c2e8bb36-703a-46ff-94ef-a440fc2ec90f)
After several minutes, there are several files under "dump" directory, I use "ls -lR" to list all files:
![2024-04-16_19-39](https://github.com/snt-arg/lidar_s_graphs/assets/36686362/cf607540-b27c-4a2e-9776-bfbfe16c34b5)
Because I don't know when the service could stop,  I'm not sure whether these files are all I can get.

**Comment by fentuoli** [comment]
For the problem above, I play another bag and call "/s_graphs/dump" service, this time it reports "requester" infomation:
![2024-04-16_19-53](https://github.com/snt-arg/lidar_s_graphs/assets/36686362/09b0bf85-06d4-439d-a8e6-360b980ef63d)
and I re-call "/s_graphs/dump" service, it blocks, so it cannot be called twice:)

**Comment by hridaybavle** [comment]
Hello @fentuoli, I think the dump service has some changes which are not well tested so maybe there might be some implementation issues there. What do you need it for exactly? If you just need just the .pcd of the final map you can use `save_map` service I mentioned before.

**Comment by fentuoli** [comment]
Specifically, I want to get the area of room or plane nodes' position, which I can use for some semantic navigation tasks. I notice the graph.g2o file stores 'VERTEX_ROOM' position, I can use this file. If the "/s_graphs/dump" service can also provide other information w.r.t pose, it will be helpful.

**Comment by fentuoli** [comment]
Hi, I found when I call `/s_graphs/dump service`, the hierarchical mapping results in rviz shrink from the first picture to the second picture:
![2024-04-16_19-50](https://github.com/snt-arg/lidar_s_graphs/assets/36686362/c84c974e-ff7d-4528-ac24-3a91b42ba940)
![2024-04-16_19-51](https://github.com/snt-arg/lidar_s_graphs/assets/36686362/c16f05a7-319a-4548-bc4f-75d2854def83)
What do the red dots and black dots represent respectively? Their number does not seem to match the number of walls or doors.

**Comment by hridaybavle** [comment]
If you want the planes and room centers you can directly query the topic `s_graphs/markers`, it store all the information regarding the rooms and plane centers and also stores information of the pointclouds belonging to a plane. You can use the `namespaces` filter the `s_graphs/markers` to find the keyframes, walls, rooms, floor. The red dots are just the cluster of free-space used to detect rooms. 

@shaheer34mts do you have any idea why the new dump service would take so much [time](https://github.com/snt-arg/lidar_s_graphs/issues/2#issuecomment-2058895508)?

**Comment by fentuoli** [comment]
Ok, I get it. The dump service doesn't take so much time, it just cannot be called repeatedly, otherwise it will block. If I want to call it repeatedly, I have to play the bag again. Anyway, thanks for your patience, your prompt answer saved me a lot of time.

**Comment by hridaybavle** [comment]
Closing this issue.
