### ISSUE TITLE
Dockerfile issues

### ISSUE THREAD

**Issue by m-malayeri** [snt-arg/lidar_situational_graphs#5]
Hi, there is a problem while executing `docker build` on the provided Dockerfile (both of them, Humble/Foxy).

For Foxy version, it happens at step 12/32 with below command:
`RUN source /opt/ros/foxy/setup.bash && colcon build --symlink-install`

And the error is: 
`CMake Error at CMakeLists.txt:37 (find_package): By not providing "Findndt_omp.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "ndt_omp", but CMake did not find one.`

For Humble version, the error while executing `apt install python3-catkin-tools` is:
`e: unable to locate package python3-catkin-tools`

Please let me know when you can fix these issues. Thanks!

**Comment by hridaybavle** [comment]
@m-malayeri the issue has now been fixed in the latest commit. Please check and let me know.

**Comment by m-malayeri** [comment]
@hridaybavle Thanks for your quick response, both of the docker files are now built successfully.
