### ISSUE TITLE
 Error during the graph optimize process

### ISSUE THREAD

**Issue by dongjineee** [snt-arg/lidar_situational_graphs#6]
Hello! Thank you for your wonderful work.
I am running this s_graph on a local environment.
However, I encounter an error during the graph_optimize process as shown below. 

![image](https://github.com/snt-arg/lidar_situational_graphs/assets/150753899/dc42b5c5-c63e-4f1b-b70c-15085ef63ac4)

Could you please help me with this?

**Comment by hridaybavle** [comment]
Hello @dongjineee,

Could you build the repo again with this command and try again. 

`colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo`

This above command with take more time to build but it will give you the log of which function is causing the crash.
